#!/bin/bash
for file in example_file*; do #This initializes a for loop that iterates over all files in the current directory matching the pattern example_file* using wildcard globbing.
    if [[ "${file}" == "example_file1" ]]; then #This opens a conditional if statement that checks if the current filename matches the exact string "example_file1".
        echo "Skipping the first file" #This executes a standard output command to print a specific text message to the terminal if the condition is true.
        continue #This triggers a loop control statement that skips the rest of the current iteration and jumps directly to the next file.
    fi #This is the conditional closing keyword that marks the structural end of the if statement block.
    echo "${RANDOM}" > "${file}" #This executes an output redirection that overwrites the current file with a pseudo-random integer generated by the system.
done #This is the loop termination keyword that marks the end of the for loop structure.